-- Schema backup from Render PostgreSQL

CREATE TABLE fba_products (id int4 NOT NULL, is_vatable bool, actual_weight_kg numeric, dimensional_weight_kg numeric, weight_lb numeric, length_inch numeric, width_inch numeric, height_inch numeric, freight_price_per_kg numeric, freight_cost numeric, fba_fee numeric, referral_fee numeric, buy_box_price numeric, landed_cost_usd numeric, profit_per_unit numeric, roi numeric, ninety_day_lowest_price numeric, ninety_day_lowest_roi numeric, est_sales_per_month int4, est_profit_per_month numeric, total_sales_per_month numeric, total_profit_per_month numeric, est_investment numeric, sales_rank int4, tariff_per_unit numeric, column1_pct numeric, column1_fixed_usd numeric, reciprocal_tariff numeric, total_tariff_pct numeric, created_at timestamp, updated_at timestamp, buy_price_inc_vat numeric, buy_price_ex_vat numeric, buy_price_ex_vat_usd numeric, sheet_type text NOT NULL, owner_email text NOT NULL, sku text, asin text, fnsku text, asin_link text, product_name text, supplier_name text, supplier_url text, supplier_country text, supplier_code text, order_method text, order_instructions text, hts_code_finder text, manufacturer_city text, manufacturer_postal_code text, continue_discontinue text, updated_by text, legal_category text, declaration_name text, declaration_description text, prep_required text, manufacturer_name text, shipping_route text, sales_category text, manufacturer_country_code text, sales_based_on_rank text, amazon_category text, manufacturer_address_line text, hts_code text);

CREATE TABLE fba_approvals (updated_at timestamp, product_id int4, buy_price_ex_vat numeric, buy_box_price numeric, profit_per_unit numeric, roi numeric, qty int4, total_buy_price numeric, approved_at timestamp, purchase_date date, purchase_made bool, created_at timestamp, id int4 NOT NULL, supplier_order_ref text, asin text NOT NULL, sourced_by text NOT NULL, product_name text, supplier_name text, supplier_url text, approval_status text, approved_by text, purchased_by text, rejection_reason text, asin_link text, stb_id text);

CREATE TABLE import_tracking (id int4 NOT NULL, import_date timestamp, total_rows int4, successfully_imported int4, skipped int4, status varchar, import_id varchar NOT NULL, imported_by varchar, import_mode varchar, csv_filename varchar);

CREATE TABLE fba_stb_counter (id int4 NOT NULL, current_stb int4);

CREATE TABLE audit_logs (changed_at timestamp, id int4 NOT NULL, field_name text, old_value text, new_value text, user_email text, action varchar, order_id text);

CREATE TABLE orders (weight numeric, suggested_weight numeric, label_printed bool, sheet_row int4, is_dhl bool, total_sell_price numeric, unit_buy_price_inc_vat numeric, delivery_fee_per_line numeric, s_qty numeric, b_qty numeric, qty_received numeric, discrepancy numeric, total_buy_price_inc_vat numeric, refunded bool, total_buy_price_exc_vat numeric, exception_po_created bool, created_at timestamp, updated_at timestamp, id int4 NOT NULL, goods_not_available bool, locked_at timestamp, is_multi_po bool, imported_at timestamp, locked_gbp_usd_rate numeric, order_weight numeric, shipping_cost_gbp numeric, expected_profit numeric, updated_by text, order_id text, order_date text, product_name text, status text, po_id text, exception_reason text, exception_stock_solution text, ship_by_date text, expected_delivery_date text, purchased_by text, checked_by text, buy_link text, asin text, sku text, shipstation_link text, vat_status text, supplier_order_date text, supplier_order_ref text, expected_delivery_time text, marked_dispatched_on text, refund_date text, rate_date text, locked_by text, imported_by text);

CREATE TABLE users (id int4 NOT NULL, approved bool, approved_at timestamp, created_at timestamp, updated_at timestamp, name varchar, email varchar NOT NULL, password_hash varchar, role varchar, approved_by varchar);

CREATE TABLE settings (value jsonb NOT NULL, updated_at timestamp, key varchar NOT NULL, updated_by varchar);

CREATE TABLE role_requests (id int4 NOT NULL, created_at timestamp, decided_at timestamp, current_role varchar NOT NULL, requested_role varchar NOT NULL, status varchar, decided_by varchar, user_email varchar NOT NULL, user_name varchar);

